### ISSUE TITLE
Signal

### ISSUE THREAD

**Issue by techtonik** [nayafia/awesome-maintainers#20]
> Perhaps the most surprising thing I learned about Signal when I spoke with Moxie Marlinspike, the encrypted chat service’s creator, last year at Disrupt, was that it was essentially running on a shoestring budget.

https://techcrunch.com/2018/02/21/signal-expands-into-the-signal-foundation-with-50m-from-whatsapp-co-founder-brian-acton/

**Comment by nayafia** [comment]
That's a good one! Added it to https://github.com/nayafia/lemonade-stand/pull/76 as an example of a foundation supporting open source development.
